# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbcd35b283fa09b77f7300ad5b79024166daccdea94f90b4cd35f4c24fcb4ff10e580cd0a3feb5e9883d6481c654645f8ce85bab4b36f37a3f355b4706f120f2

test:
  secret_key_base: b545ddf3296fc9f2e5943e5cbbd43f173d8bd1826b96b228cdde6c2643b0b2ed04a9d6d29dcbd446077f1cfc55a695e40cd2f5a844daf730b82a6afcd0c4dda8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
